name: debug
on: 
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - shell: bash
      env:
        FOFA_PRIVATE_KEY: ${{ secrets.FOFA_PRIVATE_KEY }}
        FOFA_API_KEY: ${{ secrets.FOFA_API_KEY }}
      run: |
        curl -sL https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz -o CloudflareST_linux_amd64.tar.gz
        tar -zxvf CloudflareST_linux_amd64.tar.gz
        chmod +x CloudflareST
        ls
        node ./src/index.js
        cat jp.txt
        ./CloudflareST -url https://st.congs.life -n 500 -tl 500 -sl 25 -dn 4 -f ./jp.txt -o result.csv
        cat result.csv
