name: Superset New Builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'superset version'
        required: false
        default: '1.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: zcong
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: zcong/superset:test-${{ github.event.inputs.version }}
        context: ./superset
        file: ./superset/Dockerfile
        build-args: |
          version=${{ github.event.inputs.version }}
